# Clean Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
#load dataset
df = pd.read_csv("D:\\Project\\AI\\emails.csv")
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [3]:
import re
from gensim.parsing.preprocessing import strip_non_alphanum, strip_multiple_whitespaces,preprocess_string, split_alphanum, strip_short, strip_numeric
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')
sno = nltk.stem.SnowballStemmer('english')
#lấy các stopword để loại bỏ

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dangh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
def clean_mail(document):
    document = document.lstrip('Subject: ')#xóa từ Subject: ở đầu mỗi văn bản
    document = re.sub(r"http\S+", "", document)#xóa link
    document = strip_non_alphanum(document).lower().strip()#loại bỏ các kí tự đặc biệt
    document = split_alphanum(document)#tách bỏ các từ ghép với số
    document = strip_short(document, minsize=2)#loại bỏ các từ đơn 
    document = strip_numeric(document)#loại bỏ các số 
    #lọc bỏ stopword
    document = [word for word in document.split() if word.lower() not in stopwords.words('english')]
        document[i] = sno.stem(document[i])
    document = " ".join(document)
    return document

In [5]:
#loại bỏ các bản ghi trùng nhau trong dữ liệu
df.drop_duplicates(inplace = True)
df

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5693 rows x 2 columns]

In [6]:
#thực hiện clean từng data
df['emailClean'] = df['text'].apply(clean_mail)

In [7]:
df.head()

,text,spam,emailClean
0,Subject: naturally irresistible your corporate...,1,natur irresist corpor ident lt realli hard rec...
1,Subject: the stock trading gunslinger fanny i...,1,stock trade gunsling fanni merril muzo colza a...
2,Subject: unbelievable new homes made easy im ...,1,nbeliev new home made easi im want show homeow...
3,Subject: 4 color printing special request add...,1,color print special request addit inform click...
4,"Subject: do not have money , get software cds ...",1,money get softwar cds softwar compat great gro...

In [ ]:
#xóa cột text ban đầu
df.drop(columns = 'text',inplace = True)

In [10]:
df

      spam                                         emailClean
0        1  natur irresist corpor ident lt realli hard rec...
1        1  stock trade gunsling fanni merril muzo colza a...
2        1  nbeliev new home made easi im want show homeow...
3        1  color print special request addit inform click...
4        1  money get softwar cds softwar compat great gro...
...    ...                                                ...
5721     0  research develop charg gpg forward shirley cre...
5722     0  receipt visit jim thank invit visit lsu shirle...
5723     0  enron case studi updat wow day super thank muc...
5724     0  interest david pleas call shirley crenshaw ass...
5725     0  news aurora updat aurora version fastest model...

[5693 rows x 2 columns]

In [9]:
#thực hiện lưu lại data ra file EmailsClean.csv
df.to_csv("D:\\Project\\AI\\EmailsClean.csv")